
# - import_tasks: helm.yml
# #   when: action == "helm"
# #   tags:
# #     - helm

- name: Install Helm
  shell: | 
    curl  https://storage.googleapis.com/kubernetes-helm/helm-v2.14.0-linux-amd64.tar.gz > /var/tmp/helm.tar.gz
    tar -zxvf /var/tmp/helm.tar.gz  --strip-components=1 -C /usr/local/bin
    helm init
  when: action == "helm"
